require('plugins')
require('settings')
require('keymappings')
require('fzf')
require('colorscheme')
-- require('lsp.lsp-config')
require('tree')
require('acc')
require('nv-compe')
require('statusline')
